"""Counting and persistence: corpora in, frequency tables on disk.

Every corpus lands as three artifacts under ``data/output``:

``counts_<corpus>.parquet``
    ``token, count`` over the whole corpus. Unfiltered — this is what rates are computed from.
``parts_<corpus>.parquet``
    ``part_id, token, count`` for the focus vocabulary, plus ``part_sizes_<corpus>.parquet``.
    Dispersion needs this; nothing else does.
``meta_<corpus>.json``
    Provenance and the denominators, so a result can be traced back to the corpus that
    produced it without re-reading gigabytes.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Iterable, Iterator
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import polars as pl

from zipf.corpora import TIERS, TierPlan, iter_documents
from zipf.counts import CorpusCounts, Document
from zipf.harvest import DOCUMENTS_PARQUET
from zipf.models import CorpusSpec, CorpusStats
from zipf.paths import OUTPUT_DIR

logger = logging.getLogger(__name__)

#: Stop counting a reference tier once it reaches this many tokens. A cap keeps build time
#: bounded; it is always logged and written into the metadata, never applied silently.
DEFAULT_TOKEN_CAP = 60_000_000

CLAUDE_SPEC = CorpusSpec(
    corpus_id="claude_main",
    text_register="assistant",
    source="Local Claude Code transcript store, assistant text blocks addressed to the user",
    licence="User's own session history; not redistributed",
    date_cutoff=None,
    contamination_note=(
        "This is the target corpus: it is entirely model-generated by construction. The "
        "date_cutoff is None meaning 'unknown', because transcripts carry per-session "
        "timestamps rather than a corpus-wide bound."
    ),
)

SIDECHAIN_SPEC = CorpusSpec(
    corpus_id="claude_sidechain",
    text_register="assistant",
    source="Local Claude Code transcript store, subagent text returned to a parent agent",
    licence="User's own session history; not redistributed",
    date_cutoff=None,
    contamination_note=(
        "Model-generated by construction. Held separate from claude_main so that habits of "
        "writing to a human are not confused with habits of writing to another agent."
    ),
)


def counts_path(corpus_id: str) -> Path:
    return OUTPUT_DIR / f"counts_{corpus_id}.parquet"


def parts_path(corpus_id: str) -> Path:
    return OUTPUT_DIR / f"parts_{corpus_id}.parquet"


def part_sizes_path(corpus_id: str) -> Path:
    return OUTPUT_DIR / f"part_sizes_{corpus_id}.parquet"


def meta_path(corpus_id: str) -> Path:
    return OUTPUT_DIR / f"meta_{corpus_id}.json"


def persist(counts: CorpusCounts, spec: CorpusSpec, *, extra: dict | None = None) -> CorpusStats:
    """Write a counted corpus to disk and return its summary."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    counts.totals_frame().write_parquet(counts_path(counts.corpus_id))
    counts.per_part_frame().write_parquet(parts_path(counts.corpus_id))
    counts.part_sizes_frame().write_parquet(part_sizes_path(counts.corpus_id))

    stats = CorpusStats(
        corpus_id=counts.corpus_id,
        documents=counts.documents,
        parts=counts.parts,
        tokens=counts.tokens,
        types=counts.types,
        built_at=datetime.now(UTC),
    )
    payload = {
        "spec": spec.model_dump(mode="json"),
        "stats": stats.model_dump(mode="json"),
        **(extra or {}),
    }
    meta_path(counts.corpus_id).write_text(json.dumps(payload, indent=2), encoding="utf-8")
    logger.info(
        "%s: %d docs, %d parts, %d tokens, %d types",
        counts.corpus_id,
        stats.documents,
        stats.parts,
        stats.tokens,
        stats.types,
    )
    return stats


def count_claude(stratum: str = "claude_main") -> CorpusCounts:
    """Count one Claude stratum from the harvested documents table."""
    if not DOCUMENTS_PARQUET.exists():
        raise FileNotFoundError(
            f"{DOCUMENTS_PARQUET} is missing. Run `uv run zipf harvest` first."
        )
    frame = pl.read_parquet(DOCUMENTS_PARQUET).filter(pl.col("corpus_id") == stratum)
    if frame.is_empty():
        raise ValueError(f"no documents for stratum {stratum!r}")
    counts = CorpusCounts(stratum)
    for part_id, text in zip(frame["part_id"], frame["text"], strict=True):
        counts.add(str(part_id), str(text), preprocessor="markdown")
    return counts


def _capped(documents: Iterable[Document], counts: CorpusCounts, cap: int) -> Iterator[Document]:
    """Stop yielding once the accumulated token count passes ``cap``."""
    for document in documents:
        if counts.tokens >= cap:
            return
        yield document


def count_reference(
    tier: TierPlan,
    focus_vocab: frozenset[str],
    *,
    token_cap: int = DEFAULT_TOKEN_CAP,
) -> CorpusCounts:
    """Count one reference tier, stopping at the token cap.

    ``focus_vocab`` restricts only the per-part table. The totals table is unfiltered, so
    every rate is computed against the corpus's real size.
    """
    # The file list comes from the tier's declared manifest, never from a glob. Globbing the
    # tier directory also sweeps up the downloader's own `.cache/huggingface` tree — lock
    # files, `.incomplete` parts and metadata sidecars — and hands them to a reader that
    # expects corpus data.
    files = [tier.directory / name for name in tier.files]
    missing = [p for p in files if not p.is_file()]
    if missing:
        raise FileNotFoundError(
            f"tier {tier.corpus_id!r} is missing {len(missing)} declared file(s), first: "
            f"{missing[0]}. Run `uv run zipf fetch --tier {tier.corpus_id}`. Refusing rather "
            "than counting a partial corpus, which would silently understate its size."
        )
    counts = CorpusCounts(tier.corpus_id, focus_vocab=focus_vocab)
    counts.extend(
        _capped(iter_documents(tier, files), counts, token_cap),
        preprocessor=tier.preprocessor,
    )
    if counts.tokens >= token_cap:
        logger.warning(
            "%s: stopped at the %d-token cap; the tier's files hold more text than was read",
            tier.corpus_id,
            token_cap,
        )
    return counts


def build_reference(
    name: str, focus_vocab: frozenset[str], *, token_cap: int = DEFAULT_TOKEN_CAP
) -> CorpusStats:
    """Count and persist one reference tier."""
    tier = TIERS[name]
    counts = count_reference(tier, focus_vocab, token_cap=token_cap)
    return persist(
        counts,
        tier.spec,
        extra={"token_cap": token_cap, "capped": counts.tokens >= token_cap},
    )


def load_totals(corpus_id: str) -> tuple[dict[str, int], int]:
    """Read a corpus's ``token -> count`` table and its true token total."""
    path = counts_path(corpus_id)
    if not path.exists():
        raise FileNotFoundError(f"{path} is missing; count the corpus first")
    frame = pl.read_parquet(path)
    mapping = dict(zip(frame["token"], frame["count"], strict=True))
    return mapping, int(frame["count"].sum())


def load_part_matrix(
    corpus_id: str, vocabulary: list[str], *, fold: dict[str, str] | None = None
) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """Build a dense ``(parts, vocab)`` count matrix and the per-part token totals.

    Dense is deliberate: 128 sessions by ~16k words is under 20 MB, and the bootstrap wants a
    matrix product rather than a sparse gather.
    """
    parts_frame = pl.read_parquet(parts_path(corpus_id))
    sizes_frame = pl.read_parquet(part_sizes_path(corpus_id)).sort("part_id")
    part_ids = sizes_frame["part_id"].to_list()
    part_index = {p: i for i, p in enumerate(part_ids)}
    vocab_index = {t: i for i, t in enumerate(vocabulary)}

    matrix = np.zeros((len(part_ids), len(vocabulary)), dtype=np.float64)
    mapping = fold or {}
    for part_id, token, count in zip(
        parts_frame["part_id"], parts_frame["token"], parts_frame["count"], strict=True
    ):
        row = part_index.get(part_id)
        # Folding accumulates: several forms land in one column, so this must add rather than
        # assign, or a lemma would report only whichever form was read last.
        column = vocab_index.get(mapping.get(token, token))
        if row is not None and column is not None:
            matrix[row, column] += count
    sizes = sizes_frame["size"].to_numpy().astype(np.float64)
    return matrix, sizes, part_ids
